stages:
  - build_dist
  - build_image

build_dist:
  image: node:10
  stage: build_dist
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - dist

build_image:
  image: docker:latest
  stage: build_image
  services:
    - docker:dind
  script:
    - docker build -t mepfront .
  only:
    - master